# Site settings
title: Dimension
email: rachelannie.harris@gmail.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/dimension-theme" # the subpath of your site, e.g. /blog
url: "https://rachelanni/rachelani.github.oi" # the base hostname & protocol for your site
author: Rachel Harris

city: Memphis
state: TN
country: United States of America
phone: (731) 433-9864

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/rachelanni
googleplus_url: https://plus.google.com/u/0/rachelannie.harris
instagram_url:
linkedin_url: https://www.linkedin.com/in/rachel-harris-
pinterest_url:
slack_url:
twitter_url: https://twitter.com/rachelanni

# Build settings
markdown: kramdown

sass:
style: compressed
